name: Generate Snake

on:
  # 允许手动触发
  workflow_dispatch:
  # 每天自动运行一次
  schedule:
    - cron: "0 0 * * *"
  # 每次推送到主分支时运行
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # 从 GitHub 贡献图生成贪吃蛇动画
      - name: generate-snake-game-from-github-contribution-grid
        uses: Platane/snk@v3.0.0
        with:
          github_user_name: Sophie618
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
      
      # 推送生成的文件到 output 分支
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
